// utils/categorySlugMapper.js

const categorySlugMapper = {
    "fruits-vegetables": "Fruits & Vegetables",
    "fresh-vegetables": "Fresh Vegetables",
    "fresh-fruits": "Fresh Fruits",
    "mangoes-melons": "Mangoes & Melons",
    "flowers-leaves": "Flowers & Leaves",
    "leafy-herbs-seasonings": "Leafy, Herbs & Seasonings",
    "exotics-premium": "Exotics & Premium",
    "organics-hydroponics": "Organics & Hydroponics",
    "sprouts": "Sprouts",
    "juices": "Juices",
    "plant": "Plant",
    "salads": "Salads",
    "bloom": "Bloom",
    "dried": "Dried",
    "atta-rice-oil-dals": "Atta, Rice, Oil & Dals",
    "masala-dry-fruits": "Masala & Dry Fruits",
    "breakfast": "Breakfast",
    "zepto-cafe": "Zepto Cafe",
    "sweet-cravings": "Sweet Cravings",
    "toys-sports": "Toys & Sports",
    "apparel-lifestyle": "Apparel & Lifestyle",
    "jewellery-accessories": "Jewellery & Accessories",
    "frozen-food": "Frozen Food",
    "ice-creams-more": "Ice Creams & More",
    "packaged-food": "Packaged Food",
    "dairy": "Dairy",
    "cold-drinks": "Cold Drinks",
    "munchies": "Munchies",
    "meat": "Meat",
    "tea": "Tea",
    "biscuits": "Biscuit",
    "makeup": "Makeup",
    "skincare": "SkinCare",
    "bath-body": "Bath & Body",
    "haircare": "HairCare",
    "cleaning": "Cleaning",
    "home-needs": "HomeNeeds",
    "books": "Books",
    "kitchen": "Kitchen",
    "electronics": "Electronics",
    "grooming": "Grooming",
    "hygiene": "Hygiene",
    "pharmacy": "Pharmacy",
    "sexual": "Sexual",
    "babycare": "BabyCare",
    "petcare": "PetCare",
    "paancorner": "PaanCorner"
  };
  
  export default categorySlugMapper;
  