// utils/categorySlugReverseMapper.js

const categorySlugReverseMapper = {
    "Atta, Rice, Oil & Dals": "atta-rice-oil-dals",
"Masala & Dry Fruits": "masala-dry-fruits",

    "Fruits & Vegetables": "fruits-vegetables",
    "Fresh Vegetables": "fresh-vegetables",
    "Fresh Fruits": "fresh-fruits",
    "Mangoes & Melons": "mangoes-melons",
    "Flowers & Leaves": "flowers-leaves",
    "Leafy, Herbs & Seasonings": "leafy-herbs-seasonings",
    "Exotics & Premium": "exotics-premium",
    "Organics & Hydroponics": "organics-hydroponics",
    "Sprouts": "sprouts",
    "Juices": "juices",
    "Plant": "plant",
    "Salads": "salads",
    "Bloom": "bloom",
    "Dried": "dried",
    "Atta, Rice, Oil & Dals": "atta-rice-oil-dals",
    "Masala & Dry Fruits": "masala-dry-fruits",
    "Breakfast": "breakfast",
    "Zepto Cafe": "zepto-cafe",
    "Sweet Cravings": "sweet-cravings",
    "Toys & Sports": "toys-sports",
    "Apparel & Lifestyle": "apparel-lifestyle",
    "Jewellery & Accessories": "jewellery-accessories",
    "Frozen Food": "frozen-food",
    "Ice Creams & More": "ice-creams-more",
    "Packaged Food": "packaged-food",
    "Dairy": "dairy",
    "Cold Drinks": "cold-drinks",
    "Munchies": "munchies",
    "Meat": "meat",
    "Tea": "tea",
    "Biscuit": "biscuits",
    "Makeup": "makeup",
    "SkinCare": "skincare",
    "Bath & Body": "bath-body",
    "HairCare": "haircare",
    "Cleaning": "cleaning",
    "HomeNeeds": "home-needs",
    "Books": "books",
    "Kitchen": "kitchen",
    "Electronics": "electronics",
    "Grooming": "grooming",
    "Hygiene": "hygiene",
    "Pharmacy": "pharmacy",
    "Sexual": "sexual",
    "BabyCare": "babycare",
    "PetCare": "petcare",
    "PaanCorner": "paancorner"
  };
  
  export default categorySlugReverseMapper;
  